const express = require('express')
const path = require('path')
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const app = express()
app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json())
app.use(cookieParser())
app.set('views', path.join(__dirname, 'vues'))
app.set('view engine', 'ejs')
app.use(express.static(path.join(__dirname, 'public')))
require('./utils/connexionDB')()
const { injecterUtilisateur } = require('./middlewares/auth')
app.use(injecterUtilisateur)
const authRoutes = require('./routes/auth')
const sallesRoutes = require('./routes/salles')
const reservationsRoutes = require('./routes/reservations')
const avisRoutes = require('./routes/avis')
const utilisateursRoutes = require('./routes/utilisateurs')
const adminSallesRoutes = require('./routes/admin_salles')
const adminAvisRoutes = require('./routes/admin_avis')
app.use('/', authRoutes)
app.use('/salles', sallesRoutes)
app.use('/reservations', reservationsRoutes)
app.use('/avis', avisRoutes)
app.use('/', utilisateursRoutes)
app.use('/', adminSallesRoutes)
app.use('/admin/avis', adminAvisRoutes)
app.get('/', async (req, res) => {
  const Salle = require('./modeles/Salle')
  // Afficher toutes les salles (ne pas masquer les salles réservées)
  const salles = await Salle.find()
  res.render('accueil', { salles })
})
const PORT = process.env.PORT || 3000
app.listen(PORT, () => {
  console.log('Serveur démarré sur le port', PORT)
})
